osx_image:
  - xcode12

language: objective-c

script:
  - cd XCTestHTMLReportSampleApp
  - rm -rf TestResults.xcresult
  - xcodebuild test -project XCTestHTMLReportSampleApp.xcodeproj -scheme XCTestHTMLReportSampleApp -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' -resultBundlePath TestResults.xcresult
  - mv TestResults.xcresult
  - swift test
  - swift build -c release
  - .build/release/xchtmlreport -h